### ISSUE TITLE
Invalid TOML: missing field `skip` at line 1 column 1

### ISSUE THREAD

**Issue by simonbcn** [ngirard/lolcate-rs#7]
```
Arch Linux
Lolcate 0.5.0
```

```
$ cat .config/lolcate/default/config.toml

description = ""

# Directories to index.
dirs = [
"/"
# "~/first/dir",
# "/second/dir"
]

# Set to either "Dirs" or "Files" to skip directories or files
# skip = "Dirs"

# Set to true if you want skip symbolic links
ignore_symlinks = true

# Set to true if you want to ignore hidden files and directories
ignore_hidden = false
```

```
$ lolcate --update
Invalid TOML: missing field `skip` at line 1 column 1
```

It's solved when I uncomment `skip` line but if this parameter is mandatory it should be uncommented in the initial file.
On the other hand in the comment created in the initial file it indicates that the values for this parameter are "_Set to either "Dirs" or "Files" to skip directories or files_" but it does not say anything about the another possible value `None`.

**Comment by ngirard** [comment]
Hey @simonbcn, thanks for notifying me!

This was just solved by PR #6.

**Comment by cryptoquick** [comment]
Hi, I'm actually still getting this error.

`cargo install lolcate-rs`

```
error: expected literal
  --> /Users/hunter/.cargo/registry/src/github.com-1ecc6299db9ec823/lolcate-rs-0.5.0/src/config.rs:31:23
   |
31 |     #[serde(default = Skip::None)]
   |                       ^^^^

error[E0277]: the trait bound `config::Config: serde::Deserialize<'_>` is not satisfied
   --> /Users/hunter/.cargo/registry/src/github.com-1ecc6299db9ec823/lolcate-rs-0.5.0/src/main.rs:103:40
    |
103 |     let config: config::Config = match read_toml_file(&toml_file, &mut buffer) {
    |                                        ^^^^^^^^^^^^^^ the trait `serde::Deserialize<'_>` is not implemented for `config::Config`
    | 
   ::: /Users/hunter/.cargo/registry/src/github.com-1ecc6299db9ec823/lolcate-rs-0.5.0/src/config.rs:46:8
    |
46  | pub fn read_toml_file<'a, 'de, P: ?Sized, T>(path: &'a P, buffer: &'de mut String) -> Result<T, Error>
    |        --------------
...
49  |     T: Deserialize<'de>,
    |        ---------------- required by this bound in `config::read_toml_file`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: failed to compile `lolcate-rs v0.5.0`, intermediate artifacts can be found at `/var/folders/gm/vkllhjvd6k32gr2xhyq_92r40000gn/T/cargo-installWNk1IN`

Caused by:
  could not compile `lolcate-rs`.
```

**Comment by ngirard** [comment]
Hey @cryptoquick,

the source code on crates.io is outdated ; the error you mentioned has been fixed since.
I'd suggest using the pre-build binaries from the latest pre-release.
Meanwhile, I'm in the process of releasing version 0.6.0, whose source code will be published to crates.io. I'll do it soon.

Cheers

**Comment by cryptoquick** [comment]
Yeah, I eventually built it with git and it worked fine.

Honestly, it wasn't quite what I expected, but I suppose I'd never used command-line databases before.
